version: '3.1'
services:
  webserver:
    build:
    #con estas dos lineas inferiores mandamos contruir 
    #la imagen necesaria de php 
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8081:80'
    volumes:
    #es necesario exponer como volumenes las dos carpetas 
    #para poder copiarlas desde el docker file 
      - './tu_codigo:/var/www/html:rw'
      - './xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    extra_hosts:
      - host.docker.internal:host-gateway