version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_PASSWORD: ragnarok
      MYSQL_ROOT_PASSWORD: ragnarok
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - mynetwork

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    volumes:
      - './tu_codigo:/var/www/html'
      - './xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - mynetwork
    depends_on:
      - mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  persistent:
